server:
  port: 8083
spring:
  application:
    name: job-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    default: dev


resume:
  service:
    url: ${RESUME_SERVICE_URL:http://localhost:8082}

ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8000}

elasticsearch:
  host: localhost
  port: 9200