server:
  port: 8085

spring:
  application:
    name: file-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  api:
    base-path: /api/v1

  jwt:
    secret: ${JWT_SECRET}

  file:
    upload-dir: ./uploads/resumes
    allowed-extensions:
      - pdf
    allowed-content-types:
      - application/pdf
    max-size-bytes: 5242880