server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: profile-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  api:
    base-path: /api/v1