server:
  port: 8087

spring:
  application:
    name: recommendation-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  api:
    base-path: /api/v1

  jwt:
    secret: ${JWT_SECRET}

  services:
    profile-service-url: http://localhost:8082
    job-service-url: http://localhost:8083
    embedding-service-url: http://localhost:8000